### ISSUE TITLE
reboot after install/uninstall

### ISSUE THREAD

**Issue by j005u** [stylesuxx/dji-hd-fpv-configurator#14]
We should reboot the device after wtfos install and uninstall actions.

While right now it mostly works, it's quite a bit of extra work to guarantee that postinst will also set up the environment correctly.

There's an issue on gl150/lt150 where the CLI doesn't work right after install for whatever reason. A reboot fixes it already, not sure if it's even worth pursuing why.

Additionally then you don't need to spin up dinit after the install. Also, if you still wanted to do that on principle anyway, then I think the postinstall script for dinit would be more appropriate.

**Comment by stylesuxx** [comment]
Restart makes sense. I tried to start dinit via postinst script but that has some really strange side effects, I documented it in the postinst file in the dint repo.

**Comment by j005u** [comment]
I fixed the issue with adb not working after wtfos-system postinstall since you need adb to trigger a reboot and maybe other post install actions in future. Released as v0.1.4.
