### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/dji-hd-fpv-configurator#3]
* [ ] Run the base boostrap setup, setup entware, opk, brick protection and so on

Entware/WTFOS bootstrap: https://github.com/fpv-wtf/wtfos/blob/main/setup/bootsrap-wtfos.sh

**Comment by j005u** [comment]
I refactored the current margerine implementation into a separate file here: https://github.com/fpv-wtf/margerine/blob/1.1-wip/src/payload.js. But really it's just adb push https://github.com/fpv-wtf/wtfos/releases/latest/download/setup-payload.tgz /tmp && untar && execute setup script.

I don't think there's much point in implementing much more adb functionality to margerine, so here perhaps it makes more sense to re-implement cleanly and not attempt to make a node+web shim for adb. 

I'll note that I currently didn't add the default-margerine-proxy (adds proxy export to mkshrc.d) to the wtfos defaults and made margerine install it separately. But if the configurator also uses the proxy, then perhaps there is not much point in doing it so.
