### ISSUE TITLE
Allow filtering packages by repo

### ISSUE THREAD

**Issue by j005u** [stylesuxx/dji-hd-fpv-configurator#6]
I think most FPV community users will not care about Entware packages and might actually be confused by them.

In that sense it would be nice to have the ability to select which repos I care about when browsing both installed and installable packages. Presuming OPKG makes it easy enough to get that info.

**Comment by stylesuxx** [comment]
Unfortunatley `opkg` does not have this functionality for whatever reason, but we could emulate it by swapping configs. We have the main config with all repos which is used by default and then we have separate configs for each custom repo and we query installable packages that way:

```
opkg -f /path/to/repo-config update
opkg -f /path/to/repo-config list
```

Not a big fan of that though. Maybe I am missing something obvious.
