### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by j005u** [stylesuxx/dji-hd-fpv-configurator#8]
If this is to become the front page of fpv.wtf then I'd like to migrate over the About page, add the new team members onto it and also have a section for asking for donations.

The sums have not been anything to write home about at this point and we'd of course need to establish how those funds are to be used, if we present fpv.wtf more as a team effort (which it would of course be if it's the configurator) rather than my project page.

**Comment by stylesuxx** [comment]
See #19 - Done.
